version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DISABLE_REDIS=false
      - REDIS_URL=redis://redis:6379
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8080}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: 